version: "3.8"
services:
  frontend:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      NUXT_PORT: 3000
      NUXT_HOST: 0.0.0.0
      TMDB_KEY: 9de3455c46013a78dec2307813890f6f
